### ISSUE TITLE
jlc produces wrong result as compared to LLVM 

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#10]
Commands for replicating the error
jlc -I$(CSMITH_HOME)/runtime -O test-wrong-result.c -o test.jlc;
clang -I$(CSMITH_HOME)/runtime -O test-wrong-result.c -o test.clang;
./test.jlc > jlc.output
./test.clang > clang.output
diff jlc.output clang.output

[wrong-result.zip](https://github.com/phate/jlm/files/5293200/wrong-result.zip)

**Comment by sjalander** [comment]
Some more examples of c-code that produce the wrong result.

[wrong-results.zip](https://github.com/phate/jlm/files/5341319/wrong-results.zip)

**Comment by phate** [comment]
I pushed a fix to master. I tried all your test files and the bug fix seems to have solved all of them.
