### ISSUE TITLE
jlc aborts due to std:range_error

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#11]
Command for replicating the error
jlc -I$(CSMITH_HOME)/runtime  -O test-range-error.c -o test.jlc

Error output:
terminate called after throwing an instance of 'std::range_error'
  what():  Bit constant value exceeds uint64 range

[range-error.zip](https://github.com/phate/jlm/files/5323048/range-error.zip)

**Comment by phate** [comment]
I pushed a fix to master.
