### ISSUE TITLE
Alias Analysis crashes when locationSet contains only DummyLocations

### ISSUE THREAD

**Issue by davidmetz** [phate/jlm#165]
Alias analysis crashes if a `locationSet` contains only `DummyLocations`.
`DummyLocations` are skipped when `memoryNodeMap` is populated in `ConstructPointsToGraph`.
As a consequence `FindModuleEscapingMemoryNodes` crashes when trying to access the map for the "dummy" `locationSet`.

As far as I can tell this can be fixed by either checking if the set is a key of `memoryNodeMap` and continuing otherwise, or by accessing `memoryNodeMap` even for `DummyLocations`.

This can be reproduced by running  
`jlc jlm-eval-suit/hls-test-suite/src/test-array.c`
followed by
`jlm-opt --llvm --AASteensgaardBasic -o /tmp/tmp-test-array-jlm-opt-out.ll /tmp/tmp-test-array-clang-out.ll`
(the -J option to explicitly specify jlm-opt passes in jlc seems to not be implemented)

**Comment by phate** [comment]
Thanks for reporting. I will take a look at it.

**Comment by phate** [comment]
I can reproduce it.
