### ISSUE TITLE
Generated executable doesn't terminate

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#17]
The attached file executes instantaneous when compiled with clang while executed for 20 minutes before killing it when compiled with jlc.

[does-not-terminate.zip](https://github.com/phate/jlm/files/5448240/does-not-terminate.zip)

**Comment by phate** [comment]
What clang version did you test this with? When I compile it with version 7 on my computer it seems to run forever. The same happens when compiled with gcc.

**Comment by phate** [comment]
When I look at the code, it also looks like an endless loop to me....

**Comment by sjalander** [comment]
llvm-10 generates an output.

**Comment by sjalander** [comment]
Another version that does not terminate.

[does-not-terminate-v1.zip](https://github.com/phate/jlm/files/5454675/does-not-terminate-v1.zip)
