### ISSUE TITLE
I can't compile it.

### ISSUE THREAD

**Issue by gino-comp** [phate/jlm#173]
build/libjlm.a(CommandLine.la):(.rodata._ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
clang-14: fatal error: linker command failed with exit code 1 (use -v to see invocation)

I am getting the error above when I type  "make all".
"$LLVMCONFIG --version" shows 14.0.6.

Have you seen this error or fixed it? 
Thanks in advance.
![Screenshot 2022-09-28 at 1 23 38 AM](https://user-images.githubusercontent.com/30883262/192594414-a6d7fe37-af74-4c54-9595-ff0eac2a4b1f.png)

**Comment by gino-comp** [comment]
> 

Thanks for the quick response. I am using Ubuntu 20.04 and I compiled LLVM from the github repo.

**Comment by gino-comp** [comment]
You were right. I could build it after I re-compiled LLVM14 with the -DLLVM_ENABLE_RTTI=ON flag.
But, it is failing c-tests. Is it supposed to be failed for should I be worried about it?

**Comment by gino-comp** [comment]
Oh, I just remembered that I didn't clean before re-trying to build it. After "make clean", it is passing tests too. Thanks!

**Comment by phate** [comment]
Ah perfect. Thanks a lot!
