### ISSUE TITLE
jlm-opt does not finish

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#18]
jlm-opt ran for 30 minutes before I killed it.

cd jlm-eval-suite/cpu2017/benchspec/CPU/502.gcc_r/build/build_base_jlc-build-m64.0000

jlc -c -o insn-attrtab.o -DSPEC -DNDEBUG -I. -I./include -I./spec_qsort -DSPEC_502 -DSPEC_AUTO_SUPPRESS_OPENMP -DIN_GCC -DHAVE_CONFIG_H -DSPEC_LP64  insn-attrtab.c

**Comment by phate** [comment]
I pushed the fixes to master. The file compiles now in tolerable time.
