### ISSUE TITLE
Alias analyses segfaults for LLVM test suite

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#190]
cd jlm-eval-suite/llvm-test-suite/build-aa/tools
jlc -DNDEBUG  -JAASteensgaardRegionAware   -w -Werror=date-time -MD -MT tools/CMakeFiles/fpcmp-target.dir/fpcmp.c.o -MF CMakeFiles/fpcmp-target.dir/fpcmp.c.o.d -o CMakeFiles/fpcmp-target.dir/fpcmp.c.o -c ../../llvm-test-suite.git/tools/fpcmp.c2

**Comment by sjalander** [comment]
#include <stdio.h>

char *load_file(const char *path) {
  FILE *fp;

  fp = fopen(path, "rb");
}

**Comment by phate** [comment]
This snippet

`
#include <stdio.h>

void
load_file(const char *path, long *size_out) 
{
  fopen(path, "rb");
}
`
compiled with

`jlc -JAASteensgaardRegionAware -c example.c`

results in a Segmentation fault.

**Comment by phate** [comment]
I believe this [line](https://github.com/phate/jlm/blob/d6200c2bac76c4dfd66824d8228b2cec291ae8f7/libjlm/src/opt/alias-analyses/Steensgaard.cpp#L1032) should not invoke FindOrInsertRegisterLocation, but [LookupRegisterLocation](https://github.com/phate/jlm/blob/d6200c2bac76c4dfd66824d8228b2cec291ae8f7/libjlm/include/jlm/opt/alias-analyses/Steensgaard.hpp#L151) instead.
