### ISSUE TITLE
Compiling polybench correlation with -O3 cause a segfault

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#27]
jlc -I. -I./utilities -DPOLYBENCH_DUMP_ARRAYS -DPOLYBENCH_USE_C99_PROTO -O3 -I. -I./utilities -DPOLYBENCH_USE_C99_PROTO ./datamining/correlation/correlation.c ./utilities/polybench.c -o build/datamining/correlation/jlc.bin -lm
Segmentation fault (core dumped)

**Comment by phate** [comment]
I cannot reproduce this problem after fixing the DNE bug. Could you be a little bite more specific, please?
