### ISSUE TITLE
enable_load_reductions(graph) in -Jred throws a type_error

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#302]
**Recreate**
Modify jlm/llvm/opt/reduction.cpp (line 134)

static void
reduce(RvsdgModule & rm, util::StatisticsCollector & statisticsCollector)
{

and disable all optimizations except the load_reduction, i.e.,
  // enable_mux_reductions(graph);
  // enable_store_reductions(graph);
  enable_load_reductions(graph);
  // enable_gamma_reductions(graph);
  // enable_unary_reductions(graph);
  // enable_binary_reductions(graph);

Compile the file separately to avoid having to comment out unused functions:
/usr/lib/llvm-16/bin/clang++ -c --std=c++17 -gdwarf-4 -g -DJLM_DEBUG -DJLM_ENABLE_ASSERTS -I. -I/usr/lib/llvm-16/include -I. -I/usr/lib/llvm-16/include -o build/jlm/llvm/opt/reduction.la jlm/llvm/opt/reduction.cpp

Then compile jlm with debug: 
make jlm-debug -j `nproc`

Then unzip the attached ZIP and type 'make'

**Output**
terminate called after throwing an instance of 'jlm::util::type_error'
  what():  Type error - expected : float, received : bit32
Aborted (core dumped)

[classify-f32.zip](https://github.com/phate/jlm/files/13560411/classify-f32.zip)

**Comment by sjalander** [comment]
It's nf->set_load_store_reducible(true); in 

static void
enable_load_reductions(jlm::rvsdg::graph & graph)

that cause the problem.

**Comment by phate** [comment]
The above examples do not reproduce the problem any longer. However, the following snippet:

```
#include <stdint.h>                                                                                    
                                                                                                       
uint8_t foo()                                                                                          
{                                                                                                      
  uint64_t bla = 1;                                                                                    
                                                                                                       
  return *((uint8_t *)(&bla));                                                                         
}
```

compiled with Store-Mux and Load-Mux reduction disabled reproduce it. It might be that the above examples work as well when Store-Mux and Load-Mux reduction are disabled, but I have not tested.

This main issue is that the Load-Store reduction does not test whether the stored value and loaded value have the same type. It should be a simple fix.
