### ISSUE TITLE
Should the [[nodiscard]] attribute be placed on both method declarations and definitions?

### ISSUE THREAD

**Issue by haved** [phate/jlm#314]
When declaring a method or function with `[[nodiscard]]` in a header file, should the corresponding function definition in the cpp file also have `[[nodiscard]]`? I tried googling a bit to see if anyone has opinions on it, but it was hard to find anything specific. It would be nice if we could agree one way or the other, since I notice I've been very inconsistent. I'm personally leaning towards only putting it at the declaration, e.g. once per function/method.

**Comment by phate** [comment]
I would say that it needs to be present on the declaration site as it is a piece of information that the compiler needs on the invocation site in order to give a warning/error. I do not see that it is also necessary on the definition site.

@caleridas : Do you know more about this?

**Comment by phate** [comment]
I consider this resolved. Do you agree @haved ?

**Comment by haved** [comment]
I agree. For the record, we only place it on the declaration.
