### ISSUE TITLE
--JAASteensgaardAgnostic cause Assertion `lambda.nfctarguments() == callNode.ninputs() - 1' failed

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#319]
**Recreate**
_make_

**Output**

jlc: jlm/llvm/opt/alias-analyses/Steensgaard.cpp:1132: auto jlm::llvm::aa::Steensgaard::AnalyzeCall(const CallNode &)::(anonymous class)::operator()(const CallNode &, const lambda::node &) const: Assertion `lambda.nfctarguments() == callNode.ninputs() - 1' failed.

[20051012-1.zip](https://github.com/phate/jlm/files/13645814/20051012-1.zip)

**Comment by phate** [comment]
Handled by PR #326
