### ISSUE TITLE
Using -JAASteensgaardAgnostic in combination with -JNodeReduction fails

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#321]
**Recreate**
_make_

**Output**

jlc: jlm/llvm/ir/operators/load.cpp:51: bool jlm::llvm::is_load_mux_reducible(const std::vector<rvsdg::output *> &): Assertion `operands.size() >= 2' failed.
make: *** [Makefile:2: all] Aborted (core dumped)

[fpcmp.zip](https://github.com/phate/jlm/files/13646328/fpcmp.zip)

**Comment by phate** [comment]
I will close this issue as I cannot reproduce it any longer. The issue was most likely fixed in #339
