### ISSUE TITLE
Andersen: Creating a ConstantArray in a delta node does not track pointees

### ISSUE THREAD

**Issue by haved** [phate/jlm#332]
Related to #323.

Take the C program
```c
static char *refarr[2] = { "Hello", "Yo!" };

int
main()
{
    return *refarr[1];
}
```
Which, unlike (#331), actually is well-formed, and does not load from NULL.
Compiling it with `jlm-opt  --AAAndersenAgnostic --NodeReduction` still crashes in the node reduction step, however,
due to a load node having no memory state edges. This is an issue caused by Andersen. It is **not** a problem in Steensgaard.

<details>
<summary>LLVM IR here</summary>

```llvm
@refarr = internal global [2 x ptr] [ptr @.str, ptr @.str.1], align 16
@.str = private unnamed_addr constant [6 x i8] c"Hello\00", align 1
@.str.1 = private unnamed_addr constant [4 x i8] c"Yo!\00", align 1

As an aside, Andersen has edges going from the `DELTA[.str]` nodes to all escaped nodes, which is based on the logic of "escaped global variables can be overridden outside the module, and point to anything escaped". These edges of course feel very superfluous, and it might be worth looking into a) making variables of non-pointer type not be 

; Function Attrs: noinline nounwind optnone sspstrong uwtable
define dso_local signext i8 @func() #0 {
  %1 = load ptr, ptr getelementptr inbounds ([2 x ptr], ptr @refarr, i64 0, i64 1), align 8
  %2 = load i8, ptr %1, align 1
  ret i8 %2
}
```
</details>
<details>
<summary>The resulting RVSDG is</summary>

![image](https://github.com/phate/jlm/assets/3748845/11e60ccb-e3e1-4f33-b678-b1fa2ca8d3bf)
</details>

<details>
<summary>Steensgaard gives the following PtG:</summary>

![image](https://github.com/phate/jlm/assets/3748845/d803db59-bf3d-4c53-bc51-42ff567a2176)
</details>

<details>
<summary>Andersen gives the following PtG:</summary>

![image](https://github.com/phate/jlm/assets/3748845/3876439e-261e-438f-b3a9-5058bd5eebd3)
</details>

As can be seen, Steensgard has more edges, but at least there are edges going from `DELTA[refarr]` to the strings.
Andersen, on the other hand, doesn't even have a `RegisterNode` for `ConstantArray:o7`.
This is why Steensgaard doesn't trigger any crashes in the node reduction pass.

**Comment by phate** [comment]
@haved What is the points-to graph from the Steensgaard analysis? I suspect it has the same problem.

Do you also have the resulting LLVM IR code? Does the problem persist if the index is changed from `0` to something else, i.e., `*refarr[0]` to `*refarr[2]`? This might introduce a getelementpr, but I cannot determine by just looking at this whether the points-to graph will be "fixed".

**Comment by haved** [comment]
I updated the issue to use an example with getelementptr, it does not affect the points-to graph.
Steensgaard however does not have this issue, due to `ConstantArray:o0` correctly becoming a register. I'm guessing this is due to Andersen not handling aggregate types correctly, only the primitive pointer type.

**Comment by phate** [comment]
I think I discovered this problem throughout the development. It somehow rings a bell. I believe that is why Steensgaard handles it a little bit differently than just checking whether it is a pointer type:

```
Steensgaard::AnalyzeConstantArray(const jlm::rvsdg::simple_node & node)
{
  JLM_ASSERT(is<ConstantArray>(&node));


  for (size_t n = 0; n < node.ninputs(); n++)
  {
    auto input = node.input(n);


    if (LocationSet_->Contains(*input->origin()))
    {
      auto & originLocation = LocationSet_->Find(*input->origin());
      auto & outputLocation =
          LocationSet_->FindOrInsertRegisterLocation(*node.output(0), PointsToFlags::PointsToNone);
      LocationSet_->Join(outputLocation, originLocation);
    }
  }
}
```

I check whether any previous operation just inserted the values, i.e., deemed them worthy to insert due to pointers being present, instead of checking for the type. In contrast, Andersen checks for the type:

```
void
Andersen::AnalyzeConstantArray(const rvsdg::simple_node & node)
{
  JLM_ASSERT(is<ConstantArray>(&node));


  for (size_t n = 0; n < node.ninputs(); n++)
  {
    const auto & inputRegister = *node.input(n)->origin();
    if (!is<PointerType>(inputRegister.type()))
      continue;


    // TODO: Pass pointer information through aggregate types
    // Since the rest of the code only considers values of PointerType, mark inputs as escaping.
    auto inputRegisterPO = Set_->GetRegisterPointerObject(inputRegister);
    Constraints_->AddRegisterContentEscapedConstraint(inputRegisterPO);
  }
}
```
You seemed to also have been aware of this problem throughout development, as there is a TODO.

One option might be to use [IsOrContains<PointerType>()](https://github.com/phate/jlm/blob/10cbcab43fa4f98065e37c634292668c145c0f6d/jlm/llvm/ir/types.hpp#L604C1-L627C2) instead of `is<PointerType>`, but I am not sure whether this will do the trick.

**Comment by haved** [comment]
Yes the TODO is about exactly that. I mark the inputs as escaped as a fallback for not properly tracking pointees, but that doesn't help when getelementptr doesn't fallback to pointing to external when its input type is aggregate.

The correct solution is to create a function that declares which types track pointees, and which don't. It will probably just be a call to isOrContains.
