### ISSUE TITLE
Using -JAASteensgaardAgnostic -JNodeReduction throws type error for BitfieldTest

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#341]
**Recreate**
make

**Output**
jlc -w -Wno-implicit-int -JAASteensgaardAgnostic -JNodeReduction 2010-05-24-BitfieldTest.c
terminate called after throwing an instance of 'jlm::util::type_error'
  what():  Type error - expected : bit8, received : bit64

[2010-05-24-BitfieldTest.zip](https://github.com/phate/jlm/files/13848576/2010-05-24-BitfieldTest.zip)

**Comment by sjalander** [comment]
Using -JAAAndersenAgnostic -JNodeReduction has the same problem

**Comment by haved** [comment]
I also encountered this wile doing some Andersen changes, but it said `expected : bit16, received : bit64`.
I will try to figure out the root cause.
