### ISSUE TITLE
CPPFLAGS and LDFLAGS naming mismatch

### ISSUE THREAD

**Issue by phate** [phate/jlm#353]
I believe there is a discrepancy about the naming of the CPPFLAGS attribute for the individual tools in the project.

The CPPFLAGS attribute for jlc is called [jlc_EXTRA_CPPFLAGS](https://github.com/phate/jlm/blob/f0ba9b5fec9f0bddb0a0f086230676c9766c8401/tools/Makefile.sub#L14), for jhls it is called [jhls_EXTRA_CPPFLAGS](https://github.com/phate/jlm/blob/f0ba9b5fec9f0bddb0a0f086230676c9766c8401/tools/jhls/Makefile.sub#L15C1-L15C60), for jlm-hls it is called [jlm-hls_EXTRA_CPPFLAGS](https://github.com/phate/jlm/blob/f0ba9b5fec9f0bddb0a0f086230676c9766c8401/tools/jlm-hls/Makefile.sub#L19C1-L20C34), but for jlm-opt it is called [jlm-opt_CPPFLAGS](https://github.com/phate/jlm/blob/f0ba9b5fec9f0bddb0a0f086230676c9766c8401/tools/Makefile.sub#L31C1-L31C17). The [help for the common_executable macro](https://github.com/phate/jlm/blob/f0ba9b5fec9f0bddb0a0f086230676c9766c8401/Makefile.macros#L94C1-L107C73) does not mention either one of them, even though it mentions the EXTRA_LDFLAGS.

A similar issue seems to be going on for the LDFLAGS for common_executable. The help mentions EXTRA_LDFLAGS explicitly, but none of the tools uses this attribute, but rather LDFLAGS.

I am not fully sure what was exactly meant as the correct way of setting up these macros. My suspicion is that everything should be EXTRA_* and that EXTRA_CPPFLAGS needs to be added to the help, but I am not certain.

**Comment by caleridas** [comment]
yes that was actually the intent that it should all be *_EXTRA_CPPFLAGS and *_EXTRA_LDFLAGS as these should amend (_not_ override) the global CPPFLAGS/LDFLAGS

**Comment by phate** [comment]
Okay, thanks for confirming. I can draw up a PR.
