### ISSUE TITLE
Andersen shows quintic runtime

### ISSUE THREAD

**Issue by haved** [phate/jlm#366]
The comment I added in Andersen's `Solve()` function stated that the runtime can be cubic, but it can in fact be quintic on certain programs. Take the following:

```c
typedef void * voidptr;

static voidptr
    a00, a01, a02, a03, a04, a05, a06, a07, a08, a09,
    a10, a11, a12, a13, a14, a15, a16, a17, a18, a19,
    a20, a21, a22, a23, a24, a25, a26, a27, a28, a29,
    a30, a31, a32, a33, a34, a35, a36, a37, a38, a39,
    a40, a41, a42, a43, a44, a45, a46, a47, a48, a49,
    a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;

static voidptr
    b00, b01, b02, b03, b04, b05, b06, b07, b08, b09,
    b10, b11, b12, b13, b14, b15, b16, b17, b18, b19,
    b20, b21, b22, b23, b24, b25, b26, b27, b28, b29,
    b30, b31, b32, b33, b34, b35, b36, b37, b38, b39,
    b40, b41, b42, b43, b44, b45, b46, b47, b48, b49,
    b50, b51, b52, b53, b54, b55, b56, b57, b58, b59;

void init() {
    // Make a00 -> a01 -> a02 -> a03 etc.
    a00 = &a01; a01 = &a02; a02 = &a03; a03 = &a04; a04 = &a05;
    a05 = &a06; a06 = &a07; a07 = &a08; a08 = &a09; a09 = &a10;
    a10 = &a11; a11 = &a12; a12 = &a13; a13 = &a14; a14 = &a15;
    a15 = &a16; a16 = &a17; a17 = &a18; a18 = &a19; a19 = &a20;
    a20 = &a21; a21 = &a22; a22 = &a23; a23 = &a24; a24 = &a25;
    a25 = &a26; a26 = &a27; a27 = &a28; a28 = &a29; a29 = &a30;
    a30 = &a31; a31 = &a32; a32 = &a33; a33 = &a34; a34 = &a35;
    a35 = &a36; a36 = &a37; a37 = &a38; a38 = &a39; a39 = &a40;
    a40 = &a41; a41 = &a42; a42 = &a43; a43 = &a44; a44 = &a45;
    a45 = &a46; a46 = &a47; a47 = &a48; a48 = &a49; a49 = &a50;
    a50 = &a51; a51 = &a52; a52 = &a53; a53 = &a54; a54 = &a55;
    a55 = &a56; a56 = &a57; a57 = &a58; a58 = &a59;

    b00 = &a00;
}
void work() {
    b00 = b01; b01 = b02; b02 = b03; b03 = b04; b04 = b05;
    b05 = b06; b06 = b07; b07 = b08; b08 = b09; b09 = b10;
    b10 = b11; b11 = b12; b12 = b13; b13 = b14; b14 = b15;
    b15 = b16; b16 = b17; b17 = b18; b18 = b19; b19 = b20;
    b20 = b21; b21 = b22; b22 = b23; b23 = b24; b24 = b25;
    b25 = b26; b26 = b27; b27 = b28; b28 = b29; b29 = b30;
    b30 = b31; b31 = b32; b32 = b33; b33 = b34; b34 = b35;
    b35 = b36; b36 = b37; b37 = b38; b38 = b39; b39 = b40;
    b40 = b41; b41 = b42; b42 = b43; b43 = b44; b44 = b45;
    b45 = b46; b46 = b47; b47 = b48; b48 = b49; b49 = b50;
    b50 = b51; b51 = b52; b52 = b53; b53 = b54; b54 = b55;
    b55 = b56; b56 = b57; b57 = b58; b58 = b59;

    if (b00)
        b59 = *(voidptr*)b00;
}
```

It leads to `3483` constraint solving iterations, which is 59*59 + 2.
Each iteration runs 120+120+62 constraints, and each constraint application potentially looks at on the order of 120 sets, with up to 120 elements each that needs to be checked for set membership.

The total constraint solving runtime is 3.8 seconds, but it of course scales horribly.
I'm adding this as an issue mainly to track improvements with better constraint solvers.

**Comment by phate** [comment]
I am not sure I fully follow on how you end up at quintic.

**Comment by haved** [comment]
You are right. I tried analyzing increasingly large versions of the example program, and the runtime of constraint solving looks like:
![image](https://github.com/phate/jlm/assets/3748845/b7b35f85-af2c-4038-95f0-18f4a535588b)
So quartic is correct. The reason is:

 - The number of constraint iterations definitely scales with N^2. It is printed as part of the statistics.
 - The number of constraints scale with program size 
 - Almost all constraints are stores and loads to alloca variables. The stores and loads thus have only one pointee (the Alloca node). Applying the constraint thus only needs to do one subset operation (on sets of up to N elements)
 - Only the very last `b59 = *(voidptr*)b00;` performs a load with more than one pointee. It can have up to N pointees, and a subset operation is performed for each, making this constraint N^2

As you can see, there is only one constraint that actually is N^2, and not N of them, as I first thought.
However, if we just spammed the program full of `*(voidptr*)bXX`, there would be on the order of N constraints with runtime on the order of N^2.

**Comment by phate** [comment]
As discussed in the meeting, it would be nice to see a test program that illustrates the quintic runtime, and then later compare this to the cubic runtime after the worklist algorithm is implemented.

**Comment by phate** [comment]
@haved As I understood it (please correct me if I am wrong), the worlist solver should lead to a cubic runtime, right? Do you have a (contrived) program that triggers the worst-case runtime for both, the naive and worklist solver? How do the plots look like?

**Comment by haved** [comment]
Yes! I modified the program shown above slightly to make it worse, in the following way:

<details>
<summary>Program example</summary>

All variables named `aXXX` point to all variables named `xXXX`.
In addition, a001 points to a002, a002 to a003 etc.
The bXXX variables will slowly point to more and more of the aXXX variables.
It takes N^2 iterations of constraint application before the last bXXX points to the last aXXX.

The N lines of cXXX = *bXXX load from the bXXX variables, and since bXXX eventually point to N aXXX, and each aXXX points to N xXXX, each of these lines take N^2 to run. This means one pass of constraint application has N^3 runtime.

```c
typedef void * voidptr;
static int x000, x001, x002, x003, x004;
static voidptr a000, a001, a002, a003, a004;
static voidptr b000, b001, b002, b003, b004;
static voidptr c000, c001, c002, c003, c004;
void init() {
        int* x;
        x = &x000;
        x = &x001;
        x = &x002;
        x = &x003;
        x = &x004;
        a000 = x;
        a001 = x;
        a002 = x;
        a003 = x;
        a004 = x;
        a000 = &a001;
        a001 = &a002;
        a002 = &a003;
        a003 = &a004;

        b004 = &a000;
}
void work() {
        b000 = b001;
        b001 = b002;
        b002 = b003;
        b003 = b004;

        if(!b000)
                return;
        c000 = *(voidptr*)b000;
        c001 = *(voidptr*)b001;
        c002 = *(voidptr*)b002;
        c003 = *(voidptr*)b003;
        c004 = *(voidptr*)b004;
        b004 = *(voidptr*)b000;
}
```
</details>

Then I pass this to jlm-opt for every value N={10, 15, 20, 25 ... 90}, and get the following graph:
The y axis is solving time in seconds, and the X-axis is number of PointerObjects (called variables in the literature):
![image](https://github.com/phate/jlm/assets/3748845/1fae0db1-d75b-492a-b451-78b8fe58726f)

The worklist solver handles this a lot better, so I ran it up to N=205
![image](https://github.com/phate/jlm/assets/3748845/0ac4be31-7fb0-42c9-8162-c77b750a3b98)

The y axis is still in seconds, so it is by all means not instant, but this is a contrived program, and the worklist currently has no cycle detection.

**Comment by phate** [comment]
This is just wonderful. Nice work!

@haved Can we consider this issue closed?

**Comment by haved** [comment]
Yes, closing it now
