### ISSUE TITLE
Compiling timeit.c with -O3 throws jive::type_error

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#40]
jlc timeit.c
Results in an object file

jlc -O3 timeit.c
Rsults in
terminate called after throwing an instance of 'jive::type_error'
  what():  Type error - expected : mem, received : iostate
Aborted (core dumped)

[timeit.zip](https://github.com/phate/jlm/files/6776978/timeit.zip)

**Comment by phate** [comment]
Fixed.
