### ISSUE TITLE
Linking causes a jive::compiler_error

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#46]
jlc -DNDEBUG -w -Werror=date-time '-DVERSION="1.00"' '-DCOMPDATE="today"' '-DCFLAGS=""' '-DHOSTNAME="thishost"' -o mason.c.o -c mason.c

Adding -03 to the above line gives the following error:
terminate called after throwing an instance of 'jive::compiler_error'
  what():  Invalid operand region.
Aborted (core dumped)

jlc -O3 mason.c.o -o mason

clang: warning: mason.c.o: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-emit-llvm' [-Wunused-command-line-argument]
terminate called after throwing an instance of 'jive::compiler_error'
  what():  Invalid operand region.
Aborted (core dumped)

[mason.zip](https://github.com/phate/jlm/files/6791683/mason.zip)

**Comment by phate** [comment]
Could you try to compile it again with a jlc build from the bugfix branch, please.

**Comment by phate** [comment]
The commit in the bugfix branch solved the issue. Externally confirmed.
