### ISSUE TITLE
Missing lambda attributeset `==` operator

### ISSUE THREAD

**Issue by ProgrammingLouis** [phate/jlm#525]
As discussed in #492, I'm working on implementing a graph equivalence function in jlm.

The issue is that the lambda `==` operator calls this attributeset `==` operator which is not implemented

In `jlm/llvm/ir/attribute.hpp` :
```c++
class attributeset final

...

bool
  operator==(const attributeset & other) const noexcept
  {
    /*
      FIXME: Ah, since this is not a real set, we cannot cheaply implement a comparison.
    */
    return false;
  }
```
Also, if I want to implement it myself there need to be a choice on the attributeset implementation here which has not been addressed.

```c++
class attributeset final

...

private:
  /*
    FIXME: Implement a proper set. Elements are not unique here.
  */
  std::vector<std::unique_ptr<attribute>> attributes_;
```

@phate @sjalander

**Comment by phate** [comment]
I can take a look at it, but it might take a while with the holidays coming up.

**Comment by phate** [comment]
I had a look at it today. I think I found a way to support with some limited engineering effort. I should have a PR ready in the next few days.

**Comment by ProgrammingLouis** [comment]
Ok, thank you.
Please tag me in the PR when it's ready.
