### ISSUE TITLE
g++ throws error when compiling parts of alias analyses

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#77]
g++ -c -g -DJIVE_DEBUG -DJLM_DEBUG -DJLM_ENABLE_ASSERTS -Wall -Wpedantic -Wextra -Wno-unused-parameter --std=c++14 -Wfatal-errors -I./external/jive/include -I/usr/lib/llvm-11/include -I./libjlm/include -o libjlm/src/opt/alias-analyses/encoders.la libjlm/src/opt/alias-analyses/encoders.cpp
In file included from libjlm/src/opt/alias-analyses/encoders.cpp:10:
./libjlm/include/jlm/opt/alias-analyses/pointsto-graph.hpp:252:2: error: declaration of ‘jlm::aa::ptg* jlm::aa::ptg::node::ptg() const’ changes meaning of ‘ptg’ [-fpermissive]
  252 |  ptg() const noexcept
      |  ^~~
compilation terminated due to -Wfatal-errors.

**Comment by phate** [comment]
The error should be resolved with the latest commit.
