### ISSUE TITLE
g++ throws an error for the alias analyses

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#81]
In file included from libjlm/src/opt/alias-analyses/encoders.cpp:10:
./libjlm/include/jlm/opt/alias-analyses/pointsto-graph.hpp:252:2: error: declaration of ‘jlm::aa::ptg* jlm::aa::ptg::node::ptg() const’ changes meaning of ‘ptg’ [-fpermissive]
  252 |  ptg() const noexcept
      |  ^~~

**Comment by phate** [comment]
The error should be resolved with the latest commit.
