### ISSUE TITLE
C-code causing jlc to generate an executable that never terminates

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#9]
Commands for replicating the error
jlc -I$(CSMITH_HOME)/runtime -O test-no-termination.c -o test.jlc;
./test.jlc

[no-termiantion.zip](https://github.com/phate/jlm/files/5292805/no-termiantion.zip)

**Comment by phate** [comment]
What exactly is the problem with this C file? Compiled with jlc, the resulting program seems to be non-terminating, but so is it when compiled with gcc or clang.

**Comment by sjalander** [comment]
clang-7 generated executable produces the following output
checksum = 846A8480
while jlc generated executable never completes.

**Comment by phate** [comment]
Closing it, as I sadly cannot reproduce the problem...
